<!-- AJAX price slider settings -->
<script type="text/javascript">
_collapse =  <?php echo (int)Mage::getStoreConfig('ajaxlist/frontend/collapse');?> ;
_horizontal_layered_navigation =  <?php echo (int)Mage::getStoreConfig('ajaxlist/frontend/horizontal_mode');?> ;
_show_count_after =  <?php echo (int)Mage::getStoreConfig('ajaxlist/multiselect/show_count');?> ;
_selected_count_label =  "<?php echo Mage::getStoreConfig('ajaxlist/multiselect/selected_count_label');?>" ;
_multiselect_label =  "<?php echo Mage::getStoreConfig('ajaxlist/multiselect/select_label');?>" ;
_use_priceslider =  <?php echo (int)Mage::getStoreConfig("ajaxlist/ajaxlist/use_priceslider") ;?> ;
</script>

